version: '3.9'

services:
  postgres:
    image: postgres:latest   # Luôn lấy bản mới nhất
    container_name: WeatherDataETL
    restart: always
    environment:
      POSTGRES_USER: TrungTruc2k6        # Username mặc định
      POSTGRES_PASSWORD: bin123456789  # Đặt mật khẩu tại đây
      POSTGRES_DB: WeatherDataETL        # Database mặc định sẽ được tạo
    ports:
      - "5433:5432"   # Mở port 5432 để kết nối từ ngoài
    volumes:
      - postgres_data:/var/lib/postgresql  # Lưu dữ liệu bền vững

volumes:
  postgres_data:
